language: python
python:
  - "2.6"
  - "2.7"
install:
 - pip install -r requirements.txt
 - pip install pylint==1.3.1
 - pip install pyflakes
 - pip install pep8
script:
  - pep8 headphones
#  - pylint --rcfile=pylintrc headphones
  - pyflakes headphones